// <auto-generated />
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(TwitchBotDbContext))]
    [Migration("20230518183458_CommandsAndSocialUnion")]
    partial class CommandsAndSocialUnion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Contracts.Database.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_name");

                    b.Property<string>("CommandOutput")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_output");

                    b.Property<int>("CommandType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("command_rype");

                    b.HasKey("Id");

                    b.ToTable("tbl_commands");
                });
#pragma warning restore 612, 618
        }
    }
}
