// <auto-generated />
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(TwitchBotDbContext))]
    partial class TwitchBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3");

            modelBuilder.Entity("Contracts.Database.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_name");

                    b.Property<string>("CommandOutput")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_output");

                    b.HasKey("Id");

                    b.ToTable("tbl_commands");
                });
#pragma warning restore 612, 618
        }
    }
}
